accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('verify-email/<str:token>/', views.verify_email_view, name='verify_email'),
    path('logout/', views.logout_view, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('ishop.urls')),

    # Password change URLs
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ishop/urls.py
from django.urls import path

from .import views

app_name = 'ishop'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('shop/create/', views.ShopCreateView.as_view(), name='shop_create'),
    path('shop/<int:pk>/', views.ShopDetailView.as_view(), name='shop_detail'),
]

templates/base.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/base.css' %}">

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}Document{% endblock title %}</title>
    </head>
    <body>
        <link rel="stylesheet" href="{% static 'css/messages.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <header>
            {% include "header.html" %}
        </header>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="message {% if message.tags %}{{ message.tags }}{% endif %}">
                        {% if message.tags %}
                            <span class="tag">{{ message.tags | upper }}</span><br>
                        {% endif %}
                        {{ message }}
                        <i class="fa-solid fa-circle-xmark"></i>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <main>
        {% block content %}
        {% endblock content %}
        </main>

        <footer>
        {% include "footer.html" %}
        </footer>

        <script src="{% static 'js/messages.js' %}"></script>
    </body>
</html>

templates/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/footer.css' %}">

<footer>
    <p>&copy; 2024 <a href='#'>iShop</a> All Rights Reserved</p>
</footer>

templates/header.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/header.css' %}">

<nav>
    <h1 class="logo"><a href="{% url 'ishop:home' %}">iShop</a></h1>
    <ul>
        <li><a href="{% url 'ishop:home' %}">Home</a></li>
        <li><a href="#">Discover</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
        {% endif %}
    </ul>
</nav>